### ISSUE TITLE
GitPrefix 2.1.5 Incompatible with pycharm 2020.1

### ISSUE THREAD

**Issue by gollum23** [syuchan1005/GitPrefix#26]
I updated manually the Gitprefix.jar file because not show update in pycham, when I restart i receive a notification that this plugin is incompatible.

![Screenshot_20200603_044148](https://user-images.githubusercontent.com/1058783/83621987-0309d280-a555-11ea-8300-d0bca3b8a0cc.png)

![Screenshot_20200603_044540](https://user-images.githubusercontent.com/1058783/83622036-1ae15680-a555-11ea-95c1-6aa1d9b6e9ee.png)

**Comment by gollum23** [comment]
Some update about this bug :eyes:

**Comment by gollum23** [comment]
:eyes:

**Comment by syuchan1005** [comment]
Sorry for the late reply.
I've changed the latest 2.1.5, please try the update again.

**Comment by gollum23** [comment]
I think you must change version, in Jetbrains page continues 2.1.5 version launched 3th june.

I don't know how compile jar file or where can i download updated jar file

**Comment by syuchan1005** [comment]
Uploaded on 06/03, but the installable version has been corrected

![image](https://user-images.githubusercontent.com/8733829/85008673-3f197600-b198-11ea-85ba-899644a1d527.png)

**Comment by gollum23** [comment]
I just downloaded last version from jetbrains page and get same error when try to install jar file.

![Screenshot_20200621_060816](https://user-images.githubusercontent.com/1058783/85223116-ed364300-b385-11ea-9312-96ef75b17374.png)

**Comment by syuchan1005** [comment]
I have uploaded v2.1.6 with more supported versions.

Please wait!

**Comment by gollum23** [comment]
Thanks :clap:

**Comment by gollum23** [comment]
I just now tried to update to 2.1.7 version and the problem persists.

I tried to update in Pycharm and Gogland apps

**Comment by agileago** [comment]
can't update the latest version

**Comment by syuchan1005** [comment]
I have submitted v2.1.8 to jetbrains.

My mistake made you wait over a month.
I'm sorry.

**Comment by gollum23** [comment]
I downloaded zip file from github, I could install but the error about the replace text problem continues

**Comment by syuchan1005** [comment]
@gollum23 Thanks testing it.
Create a separate issue for that issue.
Thanks for your help.
